openapi: 3.2.0
info:
  title: Slope Files API
  version: '1.0'
tags:
- name: Files
paths:
  /api/v1/Files/GetFiles:
    get:
      tags:
      - Files
      summary: Get all currently available latest-version files
      operationId: GetFiles
      parameters:
      - name: Folders
        in: query
        description: 'Optional parameter to filter files to specific folders. The list must be in CSV format. If folder contains a comma, make sure to surround it with double quotes. Example: folder1,folder2,"folder,3"'
        schema:
          type: string
      - name: Fields
        in: query
        description: "Optional parameter to filter the top-level fields that are returned. \nThe list must be in CSV format. Example: field1,field2,field3"
        schema:
          type: string
      - name: Limit
        in: query
        description: Optional parameter to limit the number of items returned. Default is 200.
        schema:
          type: integer
          format: int32
      - name: Offset
        in: query
        description: Optional parameter to offset the items returned. Default is 0.
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedResponseGetFilesResponseItemV1'
        '201':
          description: Created
        '400':
          description: Bad Request
        '403':
          description: Not Allowed To Access
        '429':
          description: Too Many Requests
        '404':
          description: Not Found
        '401':
          description: Unauthorized
      security:
      - API Token: []
  /api/v1/Files/GetDownloadUrl:
    post:
      tags:
      - Files
      summary: Get a temporary URL to download a file
      operationId: GetDownloadUrl
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FilePathAndVersionDtoV1'
          text/json:
            schema:
              $ref: '#/components/schemas/FilePathAndVersionDtoV1'
          application/*+json:
            schema:
              $ref: '#/components/schemas/FilePathAndVersionDtoV1'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDownloadUrlResponseV1'
        '201':
          description: Created
        '400':
          description: Bad Request
        '403':
          description: Not Allowed To Access
        '429':
          description: Too Many Requests
        '404':
          description: Not Found
        '401':
          description: Unauthorized
      security:
      - API Token: []
  /api/v1/Files/GetUploadUrl:
    post:
      tags:
      - Files
      summary: Get a temporary URL to upload a file to a certain file path via a PUT request…
      description: 'Passing in the ContentType and ContentMD5 values is optional. If provided, they will be included in the signature, but are not stored at this point.


        Exclude the ''Content-Type'' header from the PUT request if this is not set.

        If included, the ''Content-Type'' header in the PUT request must match the provided ContentType value.


        Exclude the ''ContentMD5'' header from the PUT request if this is not set.

        If included, the ''Content-MD5'' header in the PUT request must match the provided ContentMD5 value.


        NOTE: There is a 5GB limit on the size of the file.'
      operationId: GetUploadUrl
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetUploadUrlFilePathDtoV1'
          text/json:
            schema:
              $ref: '#/components/schemas/GetUploadUrlFilePathDtoV1'
          application/*+json:
            schema:
              $ref: '#/components/schemas/GetUploadUrlFilePathDtoV1'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUploadUrlResponseV1'
        '201':
          description: Created
        '400':
          description: Bad Request
        '403':
          description: Not Allowed To Access
        '429':
          description: Too Many Requests
        '404':
          description: Not Found
        '401':
          description: Unauthorized
      security:
      - API Token: []
  /api/v1/Files/SaveUpload:
    post:
      tags:
      - Files
      summary: Save the file that was uploaded via the upload url returned by the GetUploadUrl…
      operationId: SaveUpload
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaveUploadFilePathDtoV1'
          text/json:
            schema:
              $ref: '#/components/schemas/SaveUploadFilePathDtoV1'
          application/*+json:
            schema:
              $ref: '#/components/schemas/SaveUploadFilePathDtoV1'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SaveUploadResponseV1'
        '201':
          description: Created
        '400':
          description: Bad Request
        '403':
          description: Not Allowed To Access
        '429':
          description: Too Many Requests
        '404':
          description: Not Found
        '401':
          description: Unauthorized
      security:
      - API Token: []
components:
  schemas:
    GetUploadUrlFilePathDtoV1:
      type: object
      properties:
        filePath:
          type:
          - string
          - 'null'
          description: File Path
        contentType:
          type:
          - string
          - 'null'
          description: Optional File Content Type
        contentMD5:
          type:
          - string
          - 'null'
          description: Optional MD5 Hash for File Content
      additionalProperties: false
    PaginatedResponseGetFilesResponseItemV1:
      type: object
      properties:
        items:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/GetFilesResponseItemV1'
          description: Items within the page
        offset:
          type:
          - integer
          - 'null'
          description: Offset to retrieve the next page. Null when there are no further records.
          format: int32
          readOnly: true
      additionalProperties: false
      description: Paginated response that will only return an offset if there are remaining pages
    SaveUploadFilePathDtoV1:
      type: object
      properties:
        filePath:
          type:
          - string
          - 'null'
          description: File Path
        contentMD5:
          type:
          - string
          - 'null'
          description: Optional MD5 Hash for File Content
        metadata:
          type:
          - object
          - 'null'
          additionalProperties:
            type:
            - string
            - 'null'
          description: Metadata to include with the file when saved
      additionalProperties: false
    GetDownloadUrlResponseV1:
      type: object
      properties:
        downloadUrl:
          type:
          - string
          - 'null'
          description: URL to use to download file content
        metadata:
          type:
          - object
          - 'null'
          additionalProperties:
            type:
            - string
            - 'null'
          description: Metadata for the download file
      additionalProperties: false
    GetUploadUrlResponseV1:
      type: object
      properties:
        uploadUrl:
          type:
          - string
          - 'null'
          description: URL to use to upload file content
      additionalProperties: false
    FilePathAndVersionDtoV1:
      type: object
      properties:
        filePath:
          type:
          - string
          - 'null'
          description: File Path
        version:
          type:
          - integer
          - 'null'
          description: File Version
          format: int32
      additionalProperties: false
    GetFilesResponseItemV1:
      type: object
      properties:
        fileId:
          type: integer
          format: int32
        fileKey:
          type:
          - string
          - 'null'
        folder:
          type:
          - string
          - 'null'
        notes:
          type:
          - string
          - 'null'
        sizeInBytes:
          type: integer
          format: int64
        uploadedOnUtc:
          type:
          - string
          - 'null'
          format: date-time
        version:
          type: integer
          format: int32
      additionalProperties: false
    SaveUploadResponseV1:
      type: object
      properties:
        fileId:
          type: integer
          description: File ID of the saved file at the provided path
          format: int32
      additionalProperties: false
  securitySchemes:
    API_Token:
      type: http
      description: The API token received from the Authorize endpoint goes here.
      scheme: Bearer
      bearerFormat: JWT
