openapi: 3.2.0
info:
  title: Slope Reports API
  version: '1.0'
tags:
- name: Reports
paths:
  /api/v1/Reports/Workbooks/{workbookId}/Generate:
    post:
      tags:
      - Reports
      summary: Start a workbook report generation.
      operationId: GenerateWorkbookReport
      parameters:
      - name: workbookId
        in: path
        description: Workbook ID
        required: true
        schema:
          type: string
          description: Workbook ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateWorkbookReportRequestV1'
          text/json:
            schema:
              $ref: '#/components/schemas/GenerateWorkbookReportRequestV1'
          application/*+json:
            schema:
              $ref: '#/components/schemas/GenerateWorkbookReportRequestV1'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateWorkbookReportResponseV1'
        '200':
          description: Success
        '400':
          description: Bad Request
        '403':
          description: Not Allowed To Access
        '429':
          description: Too Many Requests
        '404':
          description: Not Found
        '401':
          description: Unauthorized
      security:
      - API Token: []
  /api/v1/Reports/Workbooks/Status/{generationId}:
    get:
      tags:
      - Reports
      summary: Get workbook report generation status.
      operationId: GetWorkbookReportGenerationStatus
      parameters:
      - name: generationId
        in: path
        description: Generation ID
        required: true
        schema:
          type: string
          description: Generation ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetWorkbookReportGenerationStatusResponseV1'
        '201':
          description: Created
        '400':
          description: Bad Request
        '403':
          description: Not Allowed To Access
        '429':
          description: Too Many Requests
        '404':
          description: Not Found
        '401':
          description: Unauthorized
      security:
      - API Token: []
components:
  schemas:
    GenerateWorkbookReportResponseV1:
      type: object
      properties:
        generationId:
          type:
          - string
          - 'null'
          description: Generation ID
        reportStatusUrl:
          type:
          - string
          - 'null'
          description: The status URL to use with the generation ID.
      additionalProperties: false
    GetWorkbookReportGenerationStatusResponseV1:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/ReportGenerationStatus'
        downloadUrl:
          type:
          - string
          - 'null'
          description: Download URL
        message:
          type:
          - string
          - 'null'
          description: Message
      additionalProperties: false
    WorkbookReportFormatType:
      enum:
      - Csv
      - Excel
      - Png
      type: string
    ReportGenerationStatus:
      enum:
      - Running
      - Completed
      - Failed
      type: string
    GenerateWorkbookReportRequestV1:
      type: object
      properties:
        elementId:
          type:
          - string
          - 'null'
          description: Workbook Element ID
        reportFormat:
          $ref: '#/components/schemas/WorkbookReportFormatType'
        rowLimit:
          type:
          - integer
          - 'null'
          description: Row Limit
          format: int32
        offset:
          type:
          - integer
          - 'null'
          description: Offset
          format: int32
        parameters:
          type:
          - object
          - 'null'
          additionalProperties:
            type:
            - string
            - 'null'
          description: Parameters
      additionalProperties: false
  securitySchemes:
    API_Token:
      type: http
      description: The API token received from the Authorize endpoint goes here.
      scheme: Bearer
      bearerFormat: JWT
